### ISSUE TITLE
proposal list without the DECK argument / podtoken electorate

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#175]
Would it make sense to consider the `proposal list` run without a DECK argument as referring to the standard PoB token?

**Comment by d5000** [comment]
Affirmative. :)

Implemented not only for proposal list, but also for: podtoken state and podtoken votes.

Commit: 2071615. Can be closed if there are no new problems, was pre-tested.

**Comment by buhtignew** [comment]
For the `podtoken votes` I'm getting the following error message:
```
  File "~/.local/bin/pacli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/__main__.py", line 479, in main
    fire.Fire({
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/dt_classes.py", line 222, in votes
    return self.__get_votes(proposal_or_deck, debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/dt_classes.py", line 168, in __get_votes
    proposal_id = eu.search_for_stored_tx_label("proposal", proposal)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_utils.py", line 481, in search_for_stored_tx_label
    raise ei.PacliInputDataError("Label '{}' not found.".format(identifier))
pacli.extended_interface.PacliInputDataError: Label 'None' not found.
```
The other ones seem to work as expected.

**Comment by d5000** [comment]
The `podtoken votes` command doesn't work without any argument. Either you have to enter a proposal (as positional argument) or `-m` or `-a ADDRESS`. I just checked -m and -a and they work. The help was perhaps a bit misleading so I improved it so it's clear that the command doesn't work without any argument.

The error is however ugly, so I catched it. Commit: b0df8b4

Doesn't really need testing, you can close it (leave open so you read the info).

**Comment by buhtignew** [comment]
Maybe it doesn't make sense at this stage, but what if the address would become a positional argument as the deck so as there is no need to use the `-m` flag (no address = current main address) and also to use the `-a` flag.
Also because the `-m` flag for the other commands means `--mini-id`.
We'd have too much positional arguments in this command in such a case, wouldn't we?
_
While testing this I've noticed the following:
If I run `proposal list a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a` there is the only one proposal, `37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595`, mentioned.
Then if I run `proposal voters 37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595` there is number of addresses. I've picked the last one of the list, `n3qWzoBX24abCSq8hMMzmCb8dh5ePnhdmL`, and have run `podtoken votes a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a -a n3qWzoBX24abCSq8hMMzmCb8dh5ePnhdmL` but got `'Votes cast from address: n3qWzoBX24abCSq8hMMzmCb8dh5ePnhdmL'` only.
Since the proposal `37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595` makes part of the deck `a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a` and the address `n3qWzoBX24abCSq8hMMzmCb8dh5ePnhdmL` seems to have voted for that proposal I was expecting the output to provide some result about the votes provided by that address, but I feel like I'm not fully understanding how it supposed to work in this case.

**Comment by d5000** [comment]
We're talking about `pobtoken votes` here, right? 

The reason the `-m` argument is required is the branching logic of the command. If the command is called with one positional argument and without any flags (or without `-a` and `-m`), then it assumes that to be a proposal ID, not a deck ID. Testing if it's a deck or a proposal in this case is quite slow and complicated.

That's why I'd prefer to leave it the way it is.

In theory, we could change the command variant with the proposal as main positional argument to the proposal category. This is not that complicated because the command variant uses a different main function anyway than the other variant with DECK as first argument. This would allow the change you proposed.

My argument against that was until now that the `proposal voters` command exists and the commands are a bit similar, in addition being one command more. But perhaps a command keyword like `allvotes` or `voteresults` or so would be possible. If you agree with one of these or have a good idea for the keyword I'm willing to implement these changes.

Another idea is to change `proposal voters` to proposal `enabledvoters` or something similar. This is also an easy change and would allow to use `proposal votes` for the command variant which now is `podtoken voters PROPOSAL`.

----

The response to your second issue is simple: This command displays the "enabled voters", not those who vote actively. It's the addresses which can vote on a proposal. I have changed the help a bit so it becomes clearer.

Changing this command to `enabledvoters` or so would also help to make that clearer. Only problem is that `enabledvoters` is a bit long, perhaps you have an idea?

**Comment by buhtignew** [comment]
> But perhaps a command keyword like `allvotes` or `voteresults` or so would be possible.

What about `proposal approval`, `proposal ratification` or `proposal assent`?

> Changing this command to enabledvoters or so would also help to make that clearer. Only problem is that enabledvoters is a bit long, perhaps you have an idea?

Maybe `proposal suffrage` or `proposal franchise`?

**Comment by d5000** [comment]
I like `proposal approval`, so I implemented it this way:

- `podtoken votes` - shows now only votes by address, `-m` flag is no longer necessary (see help for details)
- `proposal approval PROPOSAL` - replaces `podtoken votes PROPOSAL`
- `proposal voters` - works like before, keyword was not changed.

I also added support for address labels for `podtoken votes`. Commit is a0b8e9c.

Made also a very small bugfix in pypeerassets (only relevant for some commands with debug option but update is not a bad idea).
----

>  is it expected that until the second last block of the Voting Round 1 the output is different than from the last block of the Voting Round 1 on?

> what is the meaning of the negative "balances" in both outputs?

Both things look unexpected. Strange because I've tested that part extensively. Have to look deeper into it, so I leave this open. Can take some days.

**Comment by buhtignew** [comment]
In the mean time I'd like to ask you whether it is possible/would make sense to add  into `proposal approval` the list of addresses that have voted during the each voting round of the proposal? 

Or maybe there is such a command I'm not aware of? 

In my understanding at the moment to get the same info one needs first to list the voters (e.g.  `proposal voters 37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595`) and then running `podtoken votes a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a -a ADDRESS` for each of those addresses extract manually the searched proposal's info from each output.

**Comment by d5000** [comment]
> In the mean time I'd like to ask you whether it is possible/would make sense to add into proposal approval the list of addresses that have voted during each voting round of the proposal?

Closest one-liner is probably `pacli proposal show DECK -s -p voting_txes`, but it does not show the addresses but the voting TX IDs, and would be probably an easy addition so I'll consider it.

**Comment by d5000** [comment]
Implemented a `--voters` option for `proposal approval` showing the voting transactions and their weights.

Pre-tested. Commit is 0d7676a. Detailed testing should be done once the dPoD unittests are implemented.

**Comment by buhtignew** [comment]
There is still the following question left:
> Both things look unexpected. Strange because I've tested that part extensively. Have to look deeper into it, so I leave this open. Can take some days.

Do you prefer me to open another issue for this or you have it under your control and will make me know somehow when it solved?

**Comment by d5000** [comment]
Ah, you're right. Ok, then we can leave this open until it is solved. I'll perhaps rename the issue.

**Comment by d5000** [comment]
This was actually a mix of 2 bugs on pypeerassets, one of both was quite important:

1) `-b` option was flawed. The parser algorithm which processes the votes was not stopping correctly at the block height, instead continuing to the last block of the chain. Nevertheless `-b` influenced the result because some other parameters depended on it. The bug wasn't really severe because the blockheight function was only used by the `proposal voters` command and would not have influenced voting outcomes or so, but anyway had to be fixed.

2) The algorithm processing the voting token (SDP token, which is a PoB token) weight affected also the voters who voted with the dPoD token. This was a major problem because it could have influenced voting outcomes, and it caused also the negative values. The affected functions were not unittested still and I probably would have discovered the flaw when unittesting them, but anyway it's a relief that it's fixed now. Both voter categories were now cleanly separated, but if a voter has balance of both tokens always his full balance will be taken into account.

Commit: c495983 (on pypeerassets)

We can now close this and test it later when it's the turn of the rest of the dPoD parts.

**Comment by buhtignew** [comment]
I have only one question left:
Now both the `proposal voters 37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595 -b 134650` and the `proposal voters 37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595 -b 134651` outputs contain only one voter, while previously it was a long list.
But what is the meaning of the following sentence in the output:
```
'Note: The weight corresponds to the adjusted PoD and voting token '
'balances at the start of the epoch 168 containing the selected '
'blockheight 134651.'
```
Specifically does it mean that there is an epoch number 168? If so, what does it mean?
Or 168 is the number of voters that should be displayed?

**Comment by d5000** [comment]
Epoch is the "distribution period" where at the end a reward can be paid out if there are completed proposals. See the wiki:

> Distribution Period: A fixed interval of blocks, defined by the Deck Issuer in the initial rules, where one Token Distribution takes place. Also called epoch.

In the case of the "standard" dPoD token on Testnet the epoch has a length of 800 blocks.

**Comment by buhtignew** [comment]
Thank you for explanation!

Does the fact that `proposal voters 37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595 -b 134650` displays only one voter means that there was only one potential voter enabled for that proposal?
My assumption was that every PoB token owner would be considered as a potential voter, so the output provided before the commit c495983 (on pypeerassets) looked more expected to me because there was a long list of voters while in this case there is only one.

**Comment by d5000** [comment]
Answer is easy: this proposal was created very early and only me was testing this dPoD token then. The voting token had just been created too (it is the same one that is now the "standard" PoB token on Testnet), and my address that was the only voter was the only one that had claimed the PoB tokens until the deadline block for this epoch.

You can investigate that if you simply use the `transaction list DECK -c` command for the standard PoB token, and you'll see that the only claim transaction before block 134400 is `97e82554217ff486343833c1e8c7629d459b9a831496091da46b4096d2523815` which issues 574.5 PoB tokens to `mie75nFHrNAHHKfQ141fWfWozdMnaec8mb` and enables this address to vote.

**Comment by buhtignew** [comment]
I've got it 
And why is it that from the block 136800 on the output of the `proposal voters 37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595 -b 136800` is like this:
```
{
    'mie75nFHrNAHHKfQ141fWfWozdMnaec8mb': Decimal('109155.000000000'),
    'mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh': Decimal('5137')
}
```
While the output of the `proposal voters 37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595` is just a long list of addresses.
It's basically the list of current weighted standard dPod and dPoB tokens balances?

**Comment by d5000** [comment]
> And why is it that from the block 136800 on the output of the proposal voters 37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595 -b 136800 is like this:

I re-checked and made actually a small but important mistake when fixing that pypeerassets bug. The first address should have had less balance. Now I fixed the bugfix and re-checked and now everything looks as expected (commit 338f440 on pypeerassets).

mie75nFHrNAHHKfQ141fWfWozdMnaec8mb has voting weight 51705 due to its balance of 574.5 PoB tokens (with weight 0.9 at this block height because already one proposal had been approved, and every approved proposal reduces the number by 10 percentage points),  mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh due to 51.37 dPoD tokens (always have weight 1). The numbers are as high as they are because always the minimum possible value of the token with more decimal places (in this case: dPoD with 2 decimal places, i.e. minimum of 0.01 tokens) is the unit which gives you weight = 1.

> It's basically the list of the current weighted standard dPod and PoB tokens balances, isn't it?

Yes. I'm just realizing that the wording of the command isn't ideal here - I would expect this outcome from a command like `podtoken enabled_voters` or so, not `proposal voters`, because that output isn't related to any proposal.

I'll think about how to reorganize that. An idea could be moving it to the `podtoken` class with the following changes:

`podtoken voters [DECK]` outputs the current voting weight, and can be fine tuned by the `-b` (blockheight) parameter. If DECK not given, the standard dPoD token is used.

`podtoken voters -p PROPOSAL -p PHASE` outputs the voting weights at one of both rounds of the proposal. Should return an error if the "electorate" isn't  defined still (if the vote is in the future and the epoch where the vote takes place has still not started).

`voters` in the podtoken class would not be 100% ideal due to the `votes` command being also in that class. Your suggestion above `suffrage` could also work, or `electorate` perhaps.

**Comment by buhtignew** [comment]
>> And why is it that from the block 136800 on the output of the proposal voters 37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595 -b 136800 is like this:

What I was trying to ask, and it's still not that much clear to me right now:
- If I launch `proposal voters 37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595 -b 136799` I'm getting just one result:
```
{'mie75nFHrNAHHKfQ141fWfWozdMnaec8mb': Decimal('57450.0000000000')}
```
- If I launch `proposal voters 37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595 -b 136800` I'm getting two results:
```
{
    'mie75nFHrNAHHKfQ141fWfWozdMnaec8mb': Decimal('51705.0000000000'),
    'mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh': Decimal('5137')
}
```
- If I launch `proposal voters 37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595` I'm getting a long list of voters, and it contains the `mie75nFHrNAHHKfQ141fWfWozdMnaec8mb` address with a much higher voting weight than it had around the block `136800`.

What is not clear to me is:
1) Why there is an additional voter at the block `136800`? Is it a voter that had claimed the tokens of another proposal that has finished all his rounds in the mean time? If so do you know which one?
2) What is the list of the voters I'm getting if I'm not using the `-b` flag? Are they the voters of the moment I'm launching the command?
3) Why is it that the voting weight of the address `mie75nFHrNAHHKfQ141fWfWozdMnaec8mb` is so different when launch `proposal voters 37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595` compared to its weight at the block `136800`?
_
>  ... because already one proposal had been approved, and every approved proposal reduces the number by 10 percentage points...

I think the original idea was to reduce that PoB tokens weight by 10% on each epoch on which there are approved proposals, because if on each voting the PoB token loses its value by 10% if there are 10 proposal to vote at once the PoB tokens will lose they voting power all at once and the PoD tokens will take over too quickly.
_ 
> An idea could be moving it to the podtoken class....

Having this command in the podtoken class doesn't look to me too intuitive either, because at least in the beginning we'll have both podtoken and pobtoken owners to vote.
Maybe it can make sense just to change the word `voters` into `suffrage` or `electorate` and keep it in proposal group?
Another idea can be to move it into `token` group, but I'm not sure about, TBH.

**Comment by d5000** [comment]
> 1) Why there is an additional voter at the block `136800`? Is it a voter that had claimed the tokens of another proposal that has finished all his rounds in the mean time? If so do you know which is that proposal?

This is actually exactly the issue why I had the idea to move the command into the "podtoken" group. The token amount of the "additional voter" you're referring to is actually the tokens the donor to the selected proposal (37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595) got for his donation transaction e9b1c2c444a1be202306838a27c070611a0983293c90e7a0310db96936dd40b4. 136800 is the start block of the first epoch this voter is enabled to vote.

This outcome is a bit unintuitive, because it's independent from the proposal you enter. The outcome of `proposal voters` will be the same for all proposals from the same deck. So for me it's more intuitive if you enter this command with the Deck ID as argument, not the Proposal ID, although a secondary mode with the proposal as argument could be useful.

I also don't see a problem if it's in the `podtoken` group because the command, if we change it in the way I proposed in the last post, would take a dPoD token deck ID as an argument. It doesn't seem important to me that the voting token is a PoB token (and it can be any kind of token, depending on deck rules).

`token` would not a good command group, because this is for commands which can apply to any token. In this case we have a specific dPoD token function.

> 2) What is the list of the voters I'm getting if I'm not using the `-b` flag? Are they the voters of the moment I'm launching the command?

Yes.

> 3) Why is it that the voting weight of the address `mie75nFHrNAHHKfQ141fWfWozdMnaec8mb` is so different when I launch `proposal voters 37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595` compared to its weight at the block `136800`?

Because it's the current state of the weights based on the voting token and the dPoD tokens. There were a lot of PoB tokens claimed since block 136800, and the "main" PoB token is the voting token for this dPoD token.

**Comment by buhtignew** [comment]
> An idea could be moving it to the podtoken class...

I have thought on your idea more into depth and, contrary to what I've said previously, I consider it a very good idea now.

In fact until we don't have tokens that uses other rules that define the voting weights differently there won't even be any need to specify the deck.
And everybody would be able to see the current voters' weights or how was the same picture previously (at any block).

The idea with `podtoken voters -p PROPOSAL -p PHASE` usage mode is also very good because it will help people to see the voters weights picture in a specific phase of the specific proposal and also will warn the users if the voting phase hasn't begun yet. 

But will it be possible to use the same flag twice?

It's up to you to change the word `voters` into `electorate` or `suffrage` I agree in advance with whatever choice you consider to be the best in this case.

If you still not 100% satisfied with this idea maybe we can consider to create a separate category `electorate` with just one command `list` in it as alternative (i.e. `pacli electorate list`). But I'm not that sure about this idea, TBH.

> I think the original idea was to reduce that PoB tokens weight by 10% on each epoch on which there are approved proposals, because if on each voting the PoB token loses its value by 10% if there are 10 proposals to vote at once the PoB tokens will lose they voting power just in one epoch and the PoD tokens will take over too quickly.

I'd like to know your opinion about this my remark.

**Comment by d5000** [comment]
> I think the original idea was to reduce that PoB tokens weight by 10% on each epoch on which there are approved proposals, because if on each voting the PoB token loses its value by 10% if there are 10 proposals to vote at once the PoB tokens will lose they voting power just in one epoch and the PoD tokens will take over too quickly

I thought I had answered this, maybe I deleted the answer accidentally. This was simply a mistake in my post, it's not 10% per proposal but 10 percentage points (1.0 to 0.9 to 0.8 to 0.7 etc.) per _epoch with completed proposals_, so it's more or less like you wrote.

Regarding the double flag `-p`, this was also probably a mistake. Of course that would not work this way, we'd need two different flags.

I'll proceed moving the command into the `podtoken` group then. Once ready I'll post the commit.

**Comment by buhtignew** [comment]
Looking forward for the new upgrade.
_
> The token amount of the "additional voter" you're referring to is actually the tokens the donor to the selected proposal (37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595) got for his donation transaction e9b1c2c444a1be202306838a27c070611a0983293c90e7a0310db96936dd40b4. 136800 is the start block of the first epoch this voter is enabled to vote.

I still have some doubt about the change of the number of the voters at the block 136800.
The difference between the output of the `proposal voters 37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595 -b 136800` and `proposal voters 37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595 -b 136799` outputs is the address `mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh`.
The block `136800` is the very first block where the donors of the proposal `37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595` were enabled to claim tokens.
The proposal `37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595` refers to the deck `a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a`  (I've got it from the `proposal show 37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595 -i` output).
If I run `token transfers a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a -a mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh` I'm seeing transaction `0064a21776ddf70004d34c7a51de68de585e7ee6b5e0d5d4d43832984892077c` that has occurred at the block `137298` which is 498 blocks after the block `136800`. So it's as if the `proposal voters 37e7f1556c5e192ac782e3576b5723492daebdb884e1ce0a6d8aa89867194595 -b 136800` output were anticipating the block at which the voter actually have the mentioned voting weight.

**Comment by d5000** [comment]
You were correct, there was still a problem with the command. It processed actually more epochs that it should have.
Meanwhile I discovered another problem in pypeerassets, which allowed to create voting power out of thin air.

Both problems are fixed now, and the command was also updated as announced (I change the title of the issue accordingly). The relevant commits are:

- e98a839 for pypeerassets
- db0ff89 for pacli

The command is now called `podtoken electorate`. Proposals can be checked with the `-p` option, to see the enabled voters for each phase. More details in the help string.

There was also a new option added: With `-n` or `--next` you can check the epoch after the current block height (or the block height you give). This allows if a proposal is to be voted in the next epoch, to see how the electorate would look if the "cut" for the voting weights was at the current block, taking into account the transfers in the epoch the given block height is in. In addition this option is useful for debugging.

**Comment by buhtignew** [comment]
I've tested `podtoken electorate -b 137298`, `podtoken electorate -b 137299` and even `podtoken electorate -b 137599` and there was no `mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh: 5137.0` line that is referring to claim transaction occurred in block `137298`.

Only if I launch `podtoken electorate -b 137600` it becomes visible.

However from the block `136800` on this transaction is visible with `podtoken electorate -b 136800 -n` command.

I don't whether it's expected.

My expectation was that the `-b` flag alone would provide a more precise picture, i.e. the added weight would be visible on the very block the corresponding transaction has been claimed, while  the command used with the `-n` flag along with the `-b` would show when the newly added voting weight could be really used.

But maybe your idea here is that doing  so would just add unnecessary confusion to the user?

**Comment by d5000** [comment]
Your results are expected, because until block 137599 the relevant epoch for the voting weight calculation is the same .

As you supposed, there's a logic behind it: The `-b` parameter does not modify the principle that the dPoD token algorithm calculates the voting weight once per epoch (at the block where the epoch changes), not per block. This means that if you use it without `-n` you will get the voting height a proposal would have _if it had a voting round at that block height._

`-n` instructs the program to compute the incomplete epoch which contains the blockheight `-b`, or the current block height if used without `-b`.

> My expectation was that the -b flag alone would provide a more precise picture, i.e. the added weight would be visible on the very block the corresponding transaction has been claimed, while the command used with the -n flag along with the -b would show when the newly added voting weight could be really used.

If I interpret you right, what you expected is that if you give `-b` only the voting weight until that block would be calculated, ignoring the token transfers/claims that follow in the same epoch.

While this option would give a different picture than now `-b ` + `-n` I struggle to see an use case where you really would need to know the state at a specific block ignoring the transactions which came later in that epoch. It would also need a change directly in pypeerassets because in the current implementation the state is always calculated at the epoch change as described above.

What could be useful instead (and easy to implement) is a flag to directly point to epochs (`-e` is still free for this command), but I don't know if this would be really used.

**Comment by buhtignew** [comment]
The use case I had in mind is the highly competitive voting process in which the participants need to know in real time what the others are doing at that moment in order to decide whether to burn coins or buy additional voting tokens, for instance.
Another use case is the debugging, if we suspect something has happened on a certain block and it would be useful see complete picture.

**Comment by d5000** [comment]
> So I'd suggest us basically to rename the -b flag into the -c flag (--current_epoch), suppressing the simultaneous usage of the -c and -n flags, i.e. the -n flag would mean --next_epoch and would be used alone in place of the -c flag.

I liked about your idea that in some situations you would have one flag less.

What I'm not so convinced about is to call the flag "current_epoch" which could lead to misinterpretations because you can provide a block height to go "into the past". The best flag word I found was "state_at_block". I'm also not completely happy with the "next" flag name and have considered also something like "after", but it is serviceable I think. I have however renamed it slightly, it's now called `--next_state`.

So I changed it in the following way:

`pacli proposal electorate [TOKEN] -s BLOCKHEIGHT` gives the state of the electorate at the block height, i.e. at the start of the epoch containing that block.

`pacli proposal electorate [TOKEN] -n [BLOCKHEIGHT]` gives the next state after the block height or the current block. Like the former `-n` flag only without the `-b` flag.

I've also implemented the `-e` `--epoch` flag where you can see the state giving the number of the epoch.

> However the issue is that the user would need to know the number of the epoch

That's true. But it would be useful for more technical users which want to know rapidly the state at specific epochs, as these are like the "blocks" of the dPoD token.

----

Just a little comment on the `-b` ideas you mentioned: The first use case would be covered by `-n`. Always if you launch the command with `-n` and without "looking into the past" with a past blockheight, then the situation at the current block is computed, as the chain has no knowledge about the transactions to come.

Even for debugging the "vision per block" would not make much sense because the program does not loop through block heights when analyzing the chain state (this would be also much, much slower), but through cards (CardTransfers), i.e. the existing dPoD token transfers. It makes more sense simply to use the `token transfers` command of the token you are analyzing, or the `-d` mode of `podtoken electorate` which shows the situation epoch by epoch and inside epochs, card by card (but not block by block).

----

I hope we can close that issue now :) All new flags were pre-tested.

**Comment by buhtignew** [comment]
> `pacli proposal electorate [TOKEN] -s BLOCKHEIGHT`
> `pacli proposal electorate [TOKEN] -n [BLOCKHEIGHT]`

You mean `podtoken electorate` for sure here, don't you?
By the way the `podtoken electorate -h` output also refers to the `proposal electorate` yet. I've added this info into "Typo and improvement" issue [here](https://github.com/slimcoin-project/pacli/issues/85#proposal_electorate).

> `pacli proposal electorate [TOKEN] -n [BLOCKHEIGHT]` gives the next state after the block height or the current block. Like the former `-n` flag only *without the `-b` flag*.

You mean *without the `-s` flag*, of course here, don't you?

> The first use case would be covered by -n.

Agreed.

> ...the state at specific epochs, as these are like the "blocks" of the dPoD token.

I'm also thinking about epochs as kind of "blocks" of the dPoD token.
_
The `podtoken electorate -e` seems to refer to the epoch that starts from the block 800, the output of this command on my side is:
```
'Enabled voters and weights for token (deck) '
'a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a'


No potential voters found in this epoch.

Note: The weight corresponds to the adjusted PoD and voting token balances at the start of the epoch True containing the selected blockheight 800.
Weights are shown in minimum token units. The tokens' numbers of decimals don't matter for this view.
```

**Comment by d5000** [comment]
> You mean podtoken electorate for sure here, don't you?

Yep, corrected it both in the post and the help string.

> You mean without the -s flag, of course here, don't you?

I was referring to the former `-b` flag, i.e. now with `-n BLOCK` you get the same result you got in the earlier version with `-n -b BLOCK`. It's basically what you proposed, only that the -s name is different.

> Note: The weight corresponds to the adjusted PoD and voting token balances at the start of epoch True

Ah, that was a case still not processed by the command. You will get an error now instead if using `-e` without epoch number, as it doesn't make sense for me to choose a "default" epoch.

There were also some minor problems with the final message which were fixed. I also fixed other messages and help strings (see the respective issue #85).

Commit: 60ffe49

**Comment by buhtignew** [comment]
I was about to close this issue, but have got (hopefully) the last question to ask:
Wouldn't it make sense considering the current blockheight in case of the `-s` like it was before and also like it's for the `-n` flag right now? I.e. outputting `Error: If using -e [or -s] options you have to provide a block height[ or epoch].` only for the `podtoken electorate -e` and not for the `podtoken electorate -s` command.

**Comment by d5000** [comment]
I don't think that makes sense because `-s` without block height would cause exactly the same behaviour as the command without `-s` at all. It's simply redundant, which is minimal, but unnecessary added complexity. In the case of `-n` this is not the case.

So I'm closing now.
