### ISSUE TITLE
transaction list [RECEIVER] -x -f [BLOCK] error message

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#228]
I've just run `transaction list n3MtPoPaAREU5GEhAErBPuju83bVog2opz -x -f 632110` and got the following error message:
```
  File "~/.local/bin/pacli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/__main__.py", line 494, in main
    fire.Fire({
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_classes.py", line 1783, in list
    return ei.run_command(self.__list, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_interface.py", line 35, in run_command
    result = c(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_classes.py", line 1845, in __list
    txes = bx.show_txes(sending_address=origin, receiving_address=address_or_deck, start=from_height, end=end_height, coinbase=view_coinbase, advanced=advanced, quiet=quiet, debug=debug, burns=False, use_locator=locator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/blockexp.py", line 121, in show_txes
    blockdata = bu.show_txes_by_block(receiving_addresses=receiving_addresses, sending_addresses=sending_addresses, advanced=advanced, startblock=startblock, endblock=endblock, coinbase=coinbase, quiet=quiet, debug=debug, use_locator=use_locator, locator=locator, store_locator=use_locator)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/blockexp_utils.py", line 112, in show_txes_by_block
    percentage = round(rh / percent)
                       ~~~^~~~~~~~~
ZeroDivisionError: division by zero
```
The same for `transaction list -x -o n3MtPoPaAREU5GEhAErBPuju83bVog2opz  -f 632110` and `transaction list -x -o n3MtPoPaAREU5GEhAErBPuju83bVog2opz  -f 632110 -e 632111`.

I'm receiving no error if I run `transaction list -x -o n3MtPoPaAREU5GEhAErBPuju83bVog2opz`, `transaction list  n3MtPoPaAREU5GEhAErBPuju83bVog2opz -x`, `transaction list -x -o n3MtPoPaAREU5GEhAErBPuju83bVog2opz  -e 632111` or `transaction list n3MtPoPaAREU5GEhAErBPuju83bVog2opz -x -e 632111`.

Update 14-01-2025:

I've run `pip install --upgrade . ` on pacli folder and it looks like the issue is gone but I have an impression that the issue may appear and disappear randomly and for the moment I don't how to test to catch that possible randomness. 

In any case if I run `transaction list -x -o n3MtPoPaAREU5GEhAErBPuju83bVog2opz -f 632110 -e 632111` I'm still receiving the `ZeroDivisionError`.

After some test I've got that the error occurs when the distance between the `first_block` and the `end_block` is less or equal to 50 blocks.

Update1 31-01-2025:
I think I was able to reproduce the original error message again.
What I did was the following:
1) I've restarted slimcoind with another slimcoin's `wallet.dat` I have.
2) I've created a gateway transaction `a3abae93a647ba6581bd97288156f0ffa78634a8d4f64e7bf88c1ed753cbbceb`
3) Then I've tried to launch `transaction list  mvonBqihDaNBawMiLaxPWHHaAsnLn81Fzb -x  -f 675780` and `transaction list mkbU3SGSMxt4tjVepPHGywWWJ7gYGrhoBG -x  -f 675780` (using two addresses I have on that `wallet.dat`) and got the `ZeroDivisionError: division by zero`.
4) I've also tried to make the partial caching for one of the addresses of that `wallet.dat` launching `address cache mvonBqihDaNBawMiLaxPWHHaAsnLn81Fzb -s 675780`, but the `transaction list mvonBqihDaNBawMiLaxPWHHaAsnLn81Fzb -x  -f 675780` command's output was still  `ZeroDivisionError: division by zero`.
5) I've launched `pip install --upgrade . --break-system-packages` on my pacli folder, but that hasn't changed the situation.
6) The `transaction list mvonBqihDaNBawMiLaxPWHHaAsnLn81Fzb -x -l -f 675780` also reports the same error, although the `address cache mvonBqihDaNBawMiLaxPWHHaAsnLn81Fzb -v` output is the following:
```
Address: mvonBqihDaNBawMiLaxPWHHaAsnLn81Fzb
Block heights: []
Last checked block (hash): 000000fa4e2a1fdc5df24f83c796583c46ef5ba727c4af554cefc42e7f1e8656
Last checked block (height): 675792
First checked block height: 675780
Was this address cached discontinuously?: False
```
7) I've looked into  `blocklocator.json` and realized that there are no cached blocks for the address `mvonBqihDaNBawMiLaxPWHHaAsnLn81Fzb`, so I've launched `address cache mkbU3SGSMxt4tjVepPHGywWWJ7gYGrhoBG -s 675780 -f` and then `transaction list mkbU3SGSMxt4tjVepPHGywWWJ7gYGrhoBG -x  -l -f 675780` but the error was still there.

Update2 31-01-2025:
I've restarted `slimcoind` replacing my secondary `wallet.dat` with the main one and paradoxically enough `transaction list  mvonBqihDaNBawMiLaxPWHHaAsnLn81Fzb -x -l  -f 675780`, `transaction list  mvonBqihDaNBawMiLaxPWHHaAsnLn81Fzb -x  -f 675780`, `transaction list mkbU3SGSMxt4tjVepPHGywWWJ7gYGrhoBG -x  -f 675780` has run smoothly again.

However after I've run `transaction list  mvonBqihDaNBawMiLaxPWHHaAsnLn81Fzb -x -l  -f 675780` the next time I run it I'm yet getting the `ZeroDivisionError`.
I've tried to run `address cache mvonBqihDaNBawMiLaxPWHHaAsnLn81Fzb` but it hasn't improved the situation.

**Comment by buhtignew** [comment]
This seems to be solved, should I close it?

**Comment by buhtignew** [comment]
This seems to have been solved in the mean time, however if I run `transaction list -x -o n3MtPoPaAREU5GEhAErBPuju83bVog2opz  -f 632110 -e 632111` I'm still receiving the the `ZeroDivisionError`.

I think it's due to the fact the beginning and the end of interval are too near, i.e if I run `transaction list -x -o n3MtPoPaAREU5GEhAErBPuju83bVog2opz  -f 632110 -e 632200` I'm getting no error message.

**Comment by d5000** [comment]
Fixed. The progress indicator now will not be displayed if the "percent" value (the number of blocks to process divided by 100) is 0, so there can be no ZeroDivision anymore. This will however occur only if only a single block is processed, because I also increased the precision of the rounding here.

Commit: 3cc52a3

Can be closed.

**Comment by buhtignew** [comment]
I'm still receiving `ZeroDivisionError` if I launch `transaction list -x -o n3MtPoPaAREU5GEhAErBPuju83bVog2opz -f 632110 -e 632111`.

I'm also getting [UnboundLocalError](https://github.com/user-attachments/files/19068385/UnboundLocalError_20250304.txt) if one launches `transaction list mkbU3SGSMxt4tjVepPHGywWWJ7gYGrhoBG -x -l -f 675780 | grep a3abae93a647ba6581bd97288156f0ffa78634a8d4f64e7bf88c1ed753cbbceb` while it's running interrupts it with `CTRL-SHIFT-c` and then runs `transaction list mkbU3SGSMxt4tjVepPHGywWWJ7gYGrhoBG -x -l -f 675780` again. But maybe it's unrelated to `pacli`. However to make `transaction list mkbU3SGSMxt4tjVepPHGywWWJ7gYGrhoBG -x -l -f 675780` function again one needs to run `address cache mkbU3SGSMxt4tjVepPHGywWWJ7gYGrhoBG -v` to see the last cached block (in my case it was `675891`) and then to launch `address cache mkbU3SGSMxt4tjVepPHGywWWJ7gYGrhoBG -s 675891 -f` starting from that block on.

**Comment by d5000** [comment]
I can't reproduce any of the errors. I suspect your pacli is not updated, like already written in #224.

**Comment by buhtignew** [comment]
In the same way I did for the #224 I've run the following tests:

Changed my python version trying different python versions, unlocked my wallet, disabled my `pyenv`.

Please note that the majority of the original issues are gone with your last commit.

**Comment by buhtignew** [comment]
As result of solving the `pacli` upgrade issue I had in #224 the aforementioned error messages are gone. 
I'm going to re-check this thread again just to see whether there nothing else left and will close it without any additional comment if everything is fine.
